return require('lib.actions').register('telescope.actions', {
  ['telescope.actions.pick'] = function() vim.cmd.Telescope() end,

  ['telescope.actions.pick.file'] = function() vim.cmd.Telescope('find_files') end,
  ['telescope.actions.pick.file.recent'] = function() vim.cmd.Telescope('oldfiles') end,
  ['telescope.actions.pick.file.git'] = function() vim.cmd.Telescope('git_files') end,
  ['telescope.actions.pick.buffer'] = function() vim.cmd.Telescope('buffers') end,
  ['telescope.actions.grep'] = function() vim.cmd.Telescope('live_grep') end,
  ['telescope.actions.grep.word'] = function() vim.cmd.Telescope('grep_string') end,
  ['telescope.actions.pick.history.command'] = function() vim.cmd.Telescope('command_history') end,
  ['telescope.actions.pick.git.log'] = function() vim.cmd.Telescope('git_commits') end,
  ['telescope.actions.pick.git.status'] = function() vim.cmd.Telescope('git_status') end,
  ['telescope.actions.pick.colorscheme'] = function() vim.cmd.Telescope('colorscheme', 'enable_preview= true') end,
  ['telescope.actions.pick.line.buffer'] = function() vim.cmd.Telescope('current_buffer_fuzzy_find') end,
  ['telescope.actions.pick.autocommand'] = function() vim.cmd.Telescope('autocommands') end,
  ['telescope.actions.pick.command'] = function() vim.cmd.Telescope('commands') end,
  ['telescope.actions.pick.diagnostic'] = function() vim.cmd.Telescope('diagnostics') end,
  ['telescope.actions.pick.diagnostic.buffer'] = function() vim.cmd.Telescope('diagnostics', 'bufnr=0') end,
  ['telescope.actions.pick.help'] = function() vim.cmd.Telescope('help_tags') end,
  ['telescope.actions.pick.highlight'] = function() vim.cmd.Telescope('highlights') end,
  ['telescope.actions.pick.icon'] = function() vim.cmd.Telescope('symbols') end,
  ['telescope.actions.pick.keymap'] = function() vim.cmd.Telescope('keymaps') end,
  ['telescope.actions.pick.man'] = function() vim.cmd.Telescope('man_pages') end,
  ['telescope.actions.pick.mark'] = function() vim.cmd.Telescope('marks') end,
  ['telescope.actions.pick.tagstack'] = function() vim.cmd.Telescope('tagstack') end,
  ['telescope.actions.pick.vim.option'] = function() vim.cmd.Telescope('vim_options') end,

  ['telescope.lsp.actions.definition'] = function() vim.cmd.Telescope('lsp_definitions') end,
  ['telescope.lsp.actions.declaration'] = function() vim.cmd.Telescope('lsp_declarations') end,
  ['telescope.lsp.actions.reference'] = function() vim.cmd.Telescope('lsp_references') end,
  ['telescope.lsp.actions.implementation'] = function() vim.cmd.Telescope('lsp_implementations') end,
  ['telescope.lsp.actions.type.definition'] = function() vim.cmd.Telescope('lsp_type_definitions') end,
  ['telescope.lsp.actions.call.incoming'] = function() vim.cmd.Telescope('lsp_incoming_calls') end,
  ['telescope.lsp.actions.call.outgoing'] = function() vim.cmd.Telescope('lsp_outgoing_calls') end,
  ['telescope.lsp.actions.symbol.document'] = function() vim.cmd.Telescope('lsp_document_symbols') end,
  ['telescope.lsp.actions.symbol.workspace'] = function() vim.cmd.Telescope('lsp_workspace_symbols') end,
  ['telescope.lsp.actions.symbol.workspace.dynamic'] = function() vim.cmd.Telescope('lsp_dynamic_workspace_symbols') end,
})
