noremap('<plug>Find(file)', function()
  return pcall(require('telescope.builtin').git_files) or require('telescope.builtin').find_files()
end)
noremap('<plug>Find(buffer)', '<cmd>Telescope buffers<cr>')
noremap('<plug>Search(live)', '<cmd>Telescope live_grep<cr>')
noremap('<plug>Search(grep)', '<cmd>Telescope grep_string search=<cr>')
noremap('<plug>Help()', '<cmd>Telescope help_tags<cr>')
noremap('<plug>Find(command)', '<cmd>Telescope commands<cr>')
noremap('<plug>Find(key)', '<cmd>Telescope keymaps<cr>')
noremap('<plug>Find(symbol)', '<cmd>Telescope symbols<cr>')

nmap('<localleader><localleader>', '<plug>Find(file)')
nmap('<leader>bb', '<plug>Find(buffer)')
nmap('<leader>/', '<plug>Search(grep)')
nmap('<leader>sg', '<plug>Search(grep)')
nmap('<leader>sl', '<plug>Search(live)')
nmap('<leader>ss', '<plug>Find(symbol)')
nmap('<leader>H', '<plug>Help()')
nmap('<leader><cr>', '<plug>Find(command)')
nmap('<leader>?', '<plug>Find(key)')
