

plugin 'lsp'
-- plugin 'navigator'

plugin 'cmp'
plugin 'tmux-navigator'
plugin 'undo-tree'
plugin 'treesitter'
plugin 'languages'
-- plugin 'filer/chad-tree'
plugin 'comments'
plugin 'zoom'
plugin 'statusline'
plugin 'tags'
plugin 'blankline'
plugin 'focus'
plugin 'words'
plugin 'misc'
plugin 'minimap'
plugin 'neorg'
plugin 'autoformat'
plugin 'debug'
plugin 'cursors'
-- plugin 'neogen'
